version: "3"

services:
  mongodb:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
    volumes:
      - "mongoconfigdb:/data/configdb"
      - "mongodb:/data/db"

  opensearch:
    image: "opensearchproject/opensearch:1.1.0"
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - logger.deprecation.level=warn
      - action.auto_create_index=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - "opensearch:/usr/share/opensearch/data"

volumes:
  mongoconfigdb:
  mongodb:
  opensearch:
