version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:6.8.23
    container_name: elasticsearch
  mongo:
    image: mongo:4.4.16
    container_name: mongodb
  datainsight:
    image: ccr.ccs.tencentyun.com/megalab/datainsight:4.3.5
    container_name: datainsight
    volumes:
      - ${PWD}/graylog.conf:/products/graylog.conf
    depends_on:
      - mongo
      - elasticsearch
    command:
      - java -jar /products/graylog.jar server -f /products/graylog.conf

