version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:6.8.23
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  mongo:
    image: mongo:4.4.16
    ports:
      - 27017:27017
