version: "3"

services:
  mongodb:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
#    volumes:
#      - "mongoconfigdb:/data/configdb"
#      - "mongodb:/data/db"

  opensearch:
    image: "docker-bkrepo.cwoa.net/ce1b09/weops-docker/opeanserch:1.1.0-ik"
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - logger.deprecation.level=warn
      - action.auto_create_index=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "19200:9200"

#volumes:
#  mongodb:
#  opensearch:
